import React from "react";
import styled, { keyframes } from "styled-components";


export const Error = () => {
  return (
    <h1>Error Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim praesentium nam nihil, natus libero, maxime dolorem esse iusto incidunt maiores repellendus sint. Recusandae alias cumque minima quisquam molestias nihil consequuntur odio nobis ullam dignissimos, expedita magnam nostrum repellendus quo ea, eveniet culpa voluptatibus! Officiis alias inventore officia quae similique, facere vitae voluptas eos perspiciatis iure ea nesciunt in nemo. Enim iste voluptate recusandae, repudiandae aperiam nihil, quo animi ex sit, fugiat nemo? Sit temporibus deserunt quod rem molestiae praesentium? Similique, esse. Minus amet, quia corrupti fuga dolorum possimus consequatur sed sequi expedita facilis? Iste recusandae numquam natus amet excepturi nesciunt quod deserunt neque magni quisquam? Culpa consectetur necessitatibus inventore quis minima nihil tempore sapiente accusantium ipsa pariatur in quia eligendi molestiae cum eos doloribus optio rem perferendis error voluptatum unde, natus sequi! Perspiciatis sequi, magni mollitia minus quos ratione aut, accusamus voluptates sunt commodi tenetur labore laboriosam repellat. Dolorem dolorum distinctio, dolores autem possimus maxime at laudantium ex maiores, sint nihil. Optio omnis ex iure aut voluptatem nostrum adipisci eligendi, nam aliquid provident quod non qui illum error nihil eos eius voluptas deserunt! Blanditiis cum eius molestias quo quos labore, molestiae, officiis unde ipsa, aperiam numquam cumque dolorem voluptatibus pariatur neque sapiente quis? Libero aut deserunt vitae facere mollitia quam maxime voluptatem veritatis iure ab laudantium magni cum facilis, esse ea adipisci, reiciendis eaque incidunt ad! Tempora fugiat voluptas labore fuga id. Provident quisquam harum itaque molestiae unde veritatis, eum nisi rem quo excepturi praesentium iste? Libero debitis recusandae, sapiente voluptatum saepe praesentium ullam impedit, alias dicta ipsum unde at dolor quos expedita cum. Recusandae, officiis! Placeat error reprehenderit voluptatem id nam ratione </h1>
  );
};
